# Generated by Django 5.1.3 on 2025-01-03 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('exhibit_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_year', models.IntegerField(blank=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Экспонат',
                'verbose_name_plural': 'Экспонаты',
                'db_table': 'exhibit',
            },
        ),
        migrations.CreateModel(
            name='ExhibitionCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Категория выставок',
                'verbose_name_plural': 'Категории выставок',
                'db_table': 'exhibition_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('exhibition_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
                ('responsible_person', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Выставка',
                'verbose_name_plural': 'Выставки',
                'db_table': 'exhibition',
            },
        ),
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('museum_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Музей',
                'verbose_name_plural': 'Музеи',
                'db_table': 'museum',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MuseumRoom',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Комната музея',
                'verbose_name_plural': 'Комнаты музея',
                'db_table': 'museum_room',
                'ordering': ['room_number'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.TextField()),
                ('role', models.TextField()),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExhibitExhibition',
            fields=[
                ('exhibit', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.exhibit')),
            ],
            options={
                'db_table': 'exhibit_exhibition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExhibitionExhibitionCategory',
            fields=[
                ('exhibition', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.exhibition')),
            ],
            options={
                'db_table': 'exhibition_exhibition_category',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='exhibition',
            name='museum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.museum'),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.museumroom'),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.users'),
        ),
    ]
