# Generated by Django 5.1.3 on 2025-01-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exhibitions/'),
        ),
    ]
