# Generated by Django 5.1.3 on 2025-01-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_exhibition_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exhibits/'),
        ),
    ]
